INCLUDE "enemymacros.asm"

;Enemy types

ENEMY_MONK EQU 0

;Enemy actions

ENEMY_ACTION_IDLE EQU 0
ENEMY_ACTION_WALK_LEFT EQU 1
ENEMY_ACTION_WALK_RIGHT EQU 2
ENEMY_ACTION_JUMP EQU 3
ENEMY_ACTION_JUMP_DOWN EQU 4
ENEMY_ACTION_FIRE EQU 5
ENEMY_ACTION_IN_AIR EQU 6
ENEMY_ACTION_HURT EQU 7

;Enemy struct

ENEMY_STRUCT_SIZE EQU 4
ENEMY_ACTION EQU PLAYER_ENEMY_STRUCT_SIZE
ENEMY_ACTION_COUNTER EQU PLAYER_ENEMY_STRUCT_SIZE + 1
ENEMY_ACTIVE EQU PLAYER_ENEMY_STRUCT_SIZE + 2
ENEMY_TYPE EQU PLAYER_ENEMY_STRUCT_SIZE + 3

;Monk constants

ENEMY_MONK_SPEED EQU 2
ENEMY_MONK_JUMP_VEL EQU %10000100
ENEMY_MONK_ACTION_TIME EQU 20
ENEMY_MONK_IDLE_TIME EQU 2
ENEMY_MONK_FIRE_ANIM_TIME EQU 8

SECTION "Enemy Variables", BSS

ENEMY1_VARS : DS PLAYER_ENEMY_STRUCT_SIZE + ENEMY_STRUCT_SIZE
ENEMY2_VARS : DS PLAYER_ENEMY_STRUCT_SIZE + ENEMY_STRUCT_SIZE
ENEMY3_VARS : DS PLAYER_ENEMY_STRUCT_SIZE + ENEMY_STRUCT_SIZE
ENEMY_PROJECTILE1_LIFE : DS 1
ENEMY_PROJECTILE2_LIFE : DS 1

SECTION "Enemy Code", HOME

EnemyInitAll:
	xor a
	EnemyInit ENEMY1_VARS
	EnemyInit ENEMY2_VARS
	EnemyInit ENEMY3_VARS
	ld [ENEMY_PROJECTILE1_LIFE], a
	ld [ENEMY_PROJECTILE2_LIFE], a
	ret
	
EnemyActAll:
	EnemyCheckAlive ENEMY1_VARS, SPRITE_ENEMY1, OAM_ENEMY1
	ld a, [ENEMY1_VARS + ENEMY_ACTIVE]
	or a
	jp z, .enemy2
	EnemyThink ENEMY1_VARS, SPRITE_ENEMY1
	EnemyAct ENEMY1_VARS, SPRITE_ENEMY1, ENEMY1_ANIM
	PlayerEnemyMove ENEMY1_VARS, SPRITE_ENEMY1, ENEMY, ENEMY_MONK_SPEED
.enemy2
	ret
	